export interface Airport {
  icao: string;
  name: string;
  concessionaire: string;
}

export const airports: Airport[] = [
  { "icao": "ENAL", "name": "Ålesund airport, Vigra", "concessionaire": "Avinor" },
  { "icao": "ENAN", "name": "Andøya airport, Andenes", "concessionaire": "Forsvaret" },
  { "icao": "ENAS", "name": "Ny-Ålesund airport, Havnerabben", "concessionaire": "Kings Bay AS *" },
  { "icao": "ENAT", "name": "Alta airport", "concessionaire": "Avinor AS" },
  { "icao": "ENBL", "name": "Førde airport, Bringeland", "concessionaire": "Avinor AS" },
  { "icao": "ENBM", "name": "Voss airport, Bømoen", "concessionaire": "Voss kommune" },
  { "icao": "ENBN", "name": "Brønnøysund airport, Brønnøy", "concessionaire": "Avinor AS" },
  { "icao": "ENBO", "name": "Bodø airport", "concessionaire": "Avinor AS" },
  { "icao": "ENBR", "name": "Bergen airport, Flesland", "concessionaire": "Avinor AS" },
  { "icao": "ENBS", "name": "Båtsfjord airport", "concessionaire": "Avinor AS" },
  { "icao": "ENBV", "name": "Berlevåg airport", "concessionaire": "Avinor AS" },
  { "icao": "ENCN", "name": "Kristiansand airport, Kjevik", "concessionaire": "Avinor AS" },
  { "icao": "ENDI", "name": "Geilo airport, Dagali", "concessionaire": "Geilo lufthavn, Dagali AS" },
  { "icao": "ENDU", "name": "Bardufoss airport", "concessionaire": "Forsvaret" },
  { "icao": "ENEG", "name": "Hønefoss airport, Eggemoen", "concessionaire": "Tronrud Engineering AS" },
  { "icao": "ENEV", "name": "Harstad/Narvik airport, Evenes", "concessionaire": "Avinor AS" },
  { "icao": "ENFG", "name": "Fagernes airport, Leirin", "concessionaire": "Avinor AS" },
  { "icao": "ENFL", "name": "Florø airport", "concessionaire": "Avinor AS" },
  { "icao": "ENGK", "name": "Arendal airport, Gullknapp", "concessionaire": "Arendal lufthavn, Gullknapp AS" },
  { "icao": "ENGM", "name": "Oslo airport, Gardermoen", "concessionaire": "Oslo Lufthavn AS" },
  { "icao": "ENHA", "name": "Hamar airport, Stafsberg", "concessionaire": "Hamar kommune" },
  { "icao": "ENHD", "name": "Haugesund airport, Karmøy", "concessionaire": "Avinor AS" },
  { "icao": "ENHF", "name": "Hammerfest airport", "concessionaire": "Avinor AS" },
  { "icao": "ENHK", "name": "Hasvik airport", "concessionaire": "Avinor AS" },
  { "icao": "ENHS", "name": "Hokksund airport", "concessionaire": "Drammen flyklubb" },
  { "icao": "ENHV", "name": "Honningsvåg airport, Valan", "concessionaire": "Avinor AS" },
  { "icao": "ENJB", "name": "Tønsberg airport, Jarlsberg", "concessionaire": "Jarlsberg Fritidssenter" },
  { "icao": "ENKB", "name": "Kristiansund airport, Kvernberget", "concessionaire": "Avinor AS" },
  { "icao": "ENKJ", "name": "Kjeller airport", "concessionaire": "Kjeller Aero Senter AS" },
  { "icao": "ENKL", "name": "Gol airport, Klanten", "concessionaire": "Klanten flyklubb" },
  { "icao": "ENKR", "name": "Kirkenes airport, Høybuktmoen", "concessionaire": "Avinor AS" },
  { "icao": "ENLK", "name": "Leknes airport", "concessionaire": "Avinor AS" },
  { "icao": "ENLI", "name": "Farsund airport, Lista", "concessionaire": "Lista Lufthavn AS" },
  { "icao": "ENMH", "name": "Mehamn airport", "concessionaire": "Avinor AS" },
  { "icao": "ENML", "name": "Molde airport, Årø", "concessionaire": "Avinor AS" },
  { "icao": "ENNS", "name": "Mosjøen airport, Kjærstad", "concessionaire": "Avinor AS" },
  { "icao": "ENNA", "name": "Lakselv airport, Banak", "concessionaire": "Avinor AS" },
  { "icao": "ENNM", "name": "Namsos airport", "concessionaire": "Avinor AS" },
  { "icao": "ENNO", "name": "Notodden airport", "concessionaire": "Notodden Lufthavn AS" },
  { "icao": "ENOL", "name": "Ørland airport", "concessionaire": "Forsvaret" },
  { "icao": "ENOP", "name": "Oppdal airport, Fagerhaug", "concessionaire": "Midtnorsk Fly- og Luftsportsenter AS" },
  { "icao": "ENOV", "name": "Ørsta/Volda airport, Hovden AS", "concessionaire": "Avinor AS" },
  { "icao": "ENRA", "name": "Mo i Rana airport, Røssvoll", "concessionaire": "Avinor AS" },
  { "icao": "ENRI", "name": "Ringebu airport, Frya", "concessionaire": "Gudbrandsdal Flyklubb" },
  { "icao": "ENRK", "name": "Rakkestad airport, Åstorp", "concessionaire": "Rakkestad Flyplass AS" },
  { "icao": "ENRM", "name": "Rørvik airport, Ryum", "concessionaire": "Avinor AS" },
  { "icao": "ENRO", "name": "Røros airport", "concessionaire": "Avinor AS" },
  { "icao": "ENRS", "name": "Røst airport", "concessionaire": "Avinor AS" },
  { "icao": "ENRV", "name": "Reinsvoll airport", "concessionaire": "Gjøvik og Toten flyklubb" },
  { "icao": "ENSA", "name": "Svea airport", "concessionaire": "Store Norske Spitsbergen Grubekomp.*" },
  { "icao": "ENSB", "name": "Svalbard airport, Longyear", "concessionaire": "Avinor AS" },
  { "icao": "ENSD", "name": "Sandane airport, Anda", "concessionaire": "Avinor AS" },
  { "icao": "ENSG", "name": "Sogndal airport, Haukåsen", "concessionaire": "Avinor AS" },
  { "icao": "ENSH", "name": "Svolvær airport, Helle", "concessionaire": "Avinor AS" },
  { "icao": "ENSI", "name": "Ski airport", "concessionaire": "Follo flyklubb" },
  { "icao": "ENSK", "name": "Stokmarknes airport, Skagen", "concessionaire": "Avinor AS" },
  { "icao": "ENSM", "name": "Elverum airport, Starmoen", "concessionaire": "Norges Luftsportforbund" },
  { "icao": "ENSN", "name": "Skien airport, Geiteryggen", "concessionaire": "Skien Lufthavn AS" },
  { "icao": "ENSO", "name": "Stord airport, Sørstokken", "concessionaire": "Sunnhordland Lufthavn AS" },
  { "icao": "ENSR", "name": "Sørkjosen airport", "concessionaire": "Avinor AS" },
  { "icao": "ENSS", "name": "Vardø airport, Svartnes", "concessionaire": "Avinor AS" },
  { "icao": "ENST", "name": "Sandnessjøen airport, Stokka", "concessionaire": "Avinor AS" },
  { "icao": "ENSU", "name": "Sunndalsøra airport, Vinnu", "concessionaire": "Indre Nordmøre flyklubb" },
  { "icao": "ENTC", "name": "Tromsø airport, Langnes", "concessionaire": "Avinor AS" },
  { "icao": "ENTO", "name": "Sandefjord airport, Torp", "concessionaire": "Sandefjord Lufthavn AS" },
  { "icao": "ENTY", "name": "Tynset airport", "concessionaire": "Tynset Flyklubb" },
  { "icao": "ENVA", "name": "Trondheim airport, Værnes", "concessionaire": "Avinor AS" },
  { "icao": "ENVD", "name": "Vadsø airport", "concessionaire": "Avinor AS" },
  { "icao": "ENZV", "name": "Stavanger airport, Sola", "concessionaire": "Avinor AS" }
];
